### ISSUE TITLE
Scattergram Upload

### ISSUE THREAD

**Issue by melissa-gu** [hack4impact/next-gen-scholars#54]
Scattergram upload throwing exception (see attached file, provided by client)

[Test Data - Sheet1.zip](https://github.com/hack4impact/next-gen-scholars/files/1839938/Test.Data.-.Sheet1.zip)

@katiejiang Met with with client today, got clarification on scattergram upload issue

**Comment by emilyeverett** [comment]
Issue addressed with more clear instructions
